version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rust_api_template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application (uncomment when ready)
  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     APP_DATABASE__URL: postgresql://postgres:password@postgres:5432/rust_api_template
  #     APP_LOGGING__LEVEL: debug
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./config:/app/config:ro

volumes:
  postgres_data: