environment: "development"

server:
  host: "0.0.0.0"
  port: 8080
  timeout_seconds: 30
  max_connections: 1000
  graceful_shutdown_timeout_seconds: 30
  connection_drain_timeout_seconds: 10
  resource_cleanup_timeout_seconds: 5

database:
  url: "postgresql://postgres/rust_api_template"
  max_connections: 10
  min_connections: 1
  acquire_timeout_seconds: 30
  idle_timeout_seconds: 600
  connect_timeout_seconds: 10
  statement_timeout_seconds: 30

logging:
  level: "info"
  format: "json"
  include_location: false
  target: "stdout"

sentry:
  dsn: ""
  environment: "development"
  traces_sample_rate: 0.1
  enable_tracing: true
  max_breadcrumbs: 100
  debug: false

external_service:
  timeout_seconds: 30
  max_retries: 3
  retry_delay_ms: 1000
  circuit_breaker_enabled: false
  circuit_breaker_threshold: 5
  circuit_breaker_timeout_seconds: 60
